#!/bin/bash

tiffs=( "${@/.*/.tiff}" )
prefix=`mktemp -u --tmpdir=.`
dcraw -T -4 -w -q 3 -m 1 -v "$@"
align_image_stack -a $prefix "${tiffs[@]}"
aligned=( $prefix* )
for i in ${!tiffs[@]}; do
	mv "${aligned[$i]}" "${tiffs[$i]}"
done

