#!/bin/bash
# tonemap version 0.2
# Author Javier Celaya
# This script is released under a GPL 3 License
# A bash script to tonemap an HDR image

SELF=`basename $0`	# Ourself

displayHelp() {
	echo "Tone map an HDR picture."
	echo
	echo "Usage: $SELF [-a alpha] [-o output] image.hdr"
}

if [ $# -eq 0 ]; then
	displayHelp;exit
fi

# Maybe 0.5 is too much...
ALPHA=0.5
# test params
while getopts ha:o: argument
do
        case $argument in
                h)displayHelp;exit;;
		a)ALPHA=$OPTARG;;
		o)OUTPUT="$OPTARG";;
        esac
done
shift $(($OPTIND-1))

HDRFILE="$1"
PREFIX="${HDRFILE/.*}"
[ -z "$OUTPUT" ] && OUTPUT="${PREFIX}.tiff"

if [ -z "$HDRFILE" -o ! -f "$HDRFILE" ]; then
	displayHelp
	exit
fi

# pfstools do not deal with spaces in filenames well
# let's use a link
LINK=`mktemp -u --tmpdir=.`
HDRFILE=`readlink -f "$HDRFILE"`
ln -s "$HDRFILE" "${LINK}.${HDRFILE/*.}"
HDRFILE="${LINK}.${HDRFILE/*.}"

echo "Tone-mapping with mantiuk08 operator"
MANTIUKFILE="${PREFIX}_mantiuk.tiff"
pfsin "$HDRFILE" | pfstmo_mantiuk08 | pfsoutimgmagick -b 16 "$MANTIUKFILE"

echo "Tone-mapping with fattal02 operator"
FATTALFILE="${PREFIX}_fattal.tiff"
pfsin "$HDRFILE" | pfssize -r 0.5 | pfstmo_fattal02 -b 0.8 -n 0.025 -s 0.5 | pfssize -r 2 | pfsoutimgmagick -s -b 16 "$FATTALFILE"

echo "Creating image stack"
convert "$MANTIUKFILE" \( "$FATTALFILE" -gaussian-blur 3x1 -alpha set -channel A -evaluate multiply $ALPHA -compose overlay \) -composite "${OUTPUT}"

rm -fr $HDRFILE

